spring:
    datasource:
        url:
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    profiles:
        include: wechat
mybatis:
    type-aliases-package: cn.ninetailfox.weixin.pojo